import json
import os

nb_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# 🏆 PSTU DataThon 2026 — Official Standalone Inference & Training Notebook\n",
            "**Team Name:** NawrizTurjo  \n",
            "**LB Score Benchmark:** `0.227966`  \n",
            "**Architecture:** 10-Seed CatBoost (`depth=5`) + SMOTE(0.3) + Synthetic Test-Distribution Augmentation @ $t=0.375$\n",
            "\n",
            "--- \n",
            "## 📋 Notebook Description\n",
            "This notebook fulfills the official **Hidden Test Set (40% Weight)** requirement. It executes a fully deterministic, self-contained pipeline:\n",
            "1. **Dynamic Ingestion:** Auto-detects competition input directory (`/kaggle/input/competitions/pstu-data-thon-2026-vol-1/` or `/kaggle/input/pstu-data-thon-2026-vol-1/`).\n",
            "2. **Feature Purification:** Removes 0-variance and duplicate features, extracts 6 row-wise statistics (`mean`, `std`, `iqr`, `zero_count`, `skew`, `kurtosis`), and applies `QuantileTransformer`.\n",
            "3. **Synthetic Test Augmentation:** Bootstraps test set with calibrated $0.1\\%$ continuous multiplicative jitter (AUC 0.5122) and performs fold-safe pseudo-label retraining.\n",
            "4. **Deterministic Inference:** Generates final binary predictions at $t=0.375$ to `/kaggle/working/submission.csv`.\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ===================================================================\n",
            "# CELL 1: Imports & Reproducibility Setup\n",
            "# ===================================================================\n",
            "import numpy as np\n",
            "import pandas as pd\n",
            "import warnings, os, gc, sys, time, random, json\n",
            "from pathlib import Path\n",
            "from scipy.stats import skew, kurtosis\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "# ML Libraries\n",
            "from sklearn.preprocessing import QuantileTransformer, LabelEncoder\n",
            "from sklearn.model_selection import StratifiedKFold\n",
            "from sklearn.metrics import f1_score, roc_auc_score\n",
            "from imblearn.over_sampling import SMOTE\n",
            "from catboost import CatBoostClassifier\n",
            "from lightgbm import LGBMClassifier\n",
            "\n",
            "print(\"=\" * 75)\n",
            "print(\"  🏆 PSTU DATATHON 2026 — STANDALONE INFERENCE & TRAINING NOTEBOOK\")\n",
            "print(\"  10-Seed CatBoost Winner Solution (0.227966 LB Benchmark)\")\n",
            "print(\"=\" * 75)\n",
            "\n",
            "T_START = time.time()\n",
            "BASE_SEED = 42\n",
            "np.random.seed(BASE_SEED)\n",
            "random.seed(BASE_SEED)\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ===================================================================\n",
            "# CELL 2: Configuration & Path Auto-Detection\n",
            "# ===================================================================\n",
            "CANDIDATE_DIRS = [\n",
            "    '/kaggle/input/competitions/pstu-data-thon-2026-vol-1',\n",
            "    '/kaggle/input/pstu-data-thon-2026-vol-1',\n",
            "    'pstu-data-thon-2026-vol-1',\n",
            "    '../input/competitions/pstu-data-thon-2026-vol-1',\n",
            "    '../input/pstu-data-thon-2026-vol-1',\n",
            "    './Dataset',\n",
            "    '.'\n",
            "]\n",
            "\n",
            "DATA_DIR = None\n",
            "for d in CANDIDATE_DIRS:\n",
            "    if os.path.exists(os.path.join(d, 'train.csv')):\n",
            "        DATA_DIR = d\n",
            "        break\n",
            "\n",
            "if DATA_DIR is None:\n",
            "    raise FileNotFoundError(\"train.csv not found in candidate directories!\")\n",
            "\n",
            "CFG = {\n",
            "    'train_path': os.path.join(DATA_DIR, 'train.csv'),\n",
            "    'test_path':  os.path.join(DATA_DIR, 'test.csv'),\n",
            "    'sub_path':   os.path.join(DATA_DIR, 'sample_submission.csv'),\n",
            "    'ensemble_seeds': [42, 123, 456, 789, 999, 2026, 777, 888, 101, 202],\n",
            "    'n_folds': 5,\n",
            "    'smote_strategy': 0.3,\n",
            "    'cb_params': {\n",
            "        'loss_function': 'Logloss',\n",
            "        'eval_metric': 'F1',\n",
            "        'iterations': 5000,\n",
            "        'learning_rate': 0.015,\n",
            "        'depth': 5,\n",
            "        'l2_leaf_reg': 5.0,\n",
            "        'random_strength': 1.5,\n",
            "        'bagging_temperature': 0.8,\n",
            "        'border_count': 254,\n",
            "        'grow_policy': 'SymmetricTree',\n",
            "        'min_data_in_leaf': 50,\n",
            "        'one_hot_max_size': 10,\n",
            "        'od_type': 'Iter',\n",
            "        'od_wait': 150,\n",
            "        'thread_count': -1,\n",
            "        'verbose': 0,\n",
            "        'allow_writing_files': False,\n",
            "        'auto_class_weights': 'Balanced',\n",
            "    },\n",
            "    'synthetic_multiplier': 1.0,\n",
            "    'jitter_frac': 0.001,\n",
            "    'integer_like_threshold': 0.99,\n",
            "    'pseudo_pos_thresh': 0.90,\n",
            "    'pseudo_neg_thresh': 0.05,\n",
            "    'pseudo_relax_step': 0.05,\n",
            "    'pseudo_relax_floor_margin': 0.05,\n",
            "    'pseudo_min_accept': 20,\n",
            "    'pseudo_max_neg_pos_ratio': 10.0,\n",
            "    'winning_threshold': 0.375,\n",
            "    'enable_stage2': True,\n",
            "}\n",
            "\n",
            "print(f\"  Detected Data Directory: {DATA_DIR}\")\n",
            "print(f\"  Ensemble Seeds ({len(CFG['ensemble_seeds'])}): {CFG['ensemble_seeds']}\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ===================================================================\n",
            "# CELL 3: Data Ingestion & Preprocessing\n",
            "# ===================================================================\n",
            "train_raw = pd.read_csv(CFG['train_path'])\n",
            "test_raw  = pd.read_csv(CFG['test_path'])\n",
            "sub_raw   = pd.read_csv(CFG['sub_path'])\n",
            "\n",
            "y = train_raw['TARGET'].copy()\n",
            "if 'id' in test_raw.columns:\n",
            "    test_ids = test_raw['id'].copy()\n",
            "    X_test_raw = test_raw.drop(columns=['id'])\n",
            "else:\n",
            "    test_ids = pd.Series(range(len(test_raw)), name='id')\n",
            "    X_test_raw = test_raw.copy()\n",
            "\n",
            "X_train_raw = train_raw.drop(columns=['TARGET'])\n",
            "feat_cols = [c for c in X_train_raw.columns if c.startswith('feat_')]\n",
            "cat_cols = X_train_raw[feat_cols].select_dtypes(include=['object']).columns.tolist()\n",
            "num_cols = [c for c in feat_cols if c not in cat_cols]\n",
            "\n",
            "# Encode categoricals\n",
            "cat_encoders = {}\n",
            "X_train_cat_encoded = pd.DataFrame(index=X_train_raw.index)\n",
            "X_test_cat_encoded  = pd.DataFrame(index=X_test_raw.index)\n",
            "for col in cat_cols:\n",
            "    le = LabelEncoder()\n",
            "    all_vals = pd.concat([X_train_raw[col], X_test_raw[col]]).astype(str)\n",
            "    le.fit(all_vals)\n",
            "    X_train_cat_encoded[col] = le.transform(X_train_raw[col].astype(str)).astype(np.int32)\n",
            "    X_test_cat_encoded[col]  = le.transform(X_test_raw[col].astype(str)).astype(np.int32)\n",
            "    cat_encoders[col] = le\n",
            "\n",
            "print(f\"  Loaded Train: {train_raw.shape} | Test: {test_raw.shape}\")\n",
            "print(f\"  Target distribution: 0={(y==0).sum():,} | 1={(y==1).sum():,}\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ===================================================================\n",
            "# CELL 4: Feature Purification & 6 Row-wise Statistics\n",
            "# ===================================================================\n",
            "X_num_tr = X_train_raw[num_cols].apply(pd.to_numeric, errors='coerce').astype(np.float32)\n",
            "X_num_te = X_test_raw[num_cols].apply(pd.to_numeric, errors='coerce').astype(np.float32)\n",
            "\n",
            "# Drop zero-variance & duplicate features\n",
            "variances = X_num_tr.var()\n",
            "zero_var = variances[variances <= 1e-12].index.tolist()\n",
            "arr_tr = X_num_tr.values.astype(np.float64)\n",
            "dup_drop = set()\n",
            "sigs = {}\n",
            "for i, c in enumerate(num_cols):\n",
            "    if c in zero_var: continue\n",
            "    col = arr_tr[:, i]\n",
            "    sig = (hash(col[:500].tobytes()), hash(col[500:1000].tobytes()), int(col.var()*1e6))\n",
            "    if sig in sigs:\n",
            "        j = sigs[sig]\n",
            "        if np.array_equal(col, arr_tr[:, j]):\n",
            "            dup_drop.add(c)\n",
            "    else:\n",
            "        sigs[sig] = i\n",
            "\n",
            "all_drop = set(zero_var) | dup_drop\n",
            "keep_num = [c for c in num_cols if c not in all_drop]\n",
            "X_num_tr = X_num_tr[keep_num]\n",
            "X_num_te = X_num_te[keep_num]\n",
            "\n",
            "def compute_row_stats(arr_np):\n",
            "    stats = {}\n",
            "    stats['row_mean'] = arr_np.mean(axis=1).astype(np.float32)\n",
            "    stats['row_std']  = arr_np.std(axis=1).astype(np.float32)\n",
            "    stats['row_iqr']  = (np.percentile(arr_np, 75, axis=1) - np.percentile(arr_np, 25, axis=1)).astype(np.float32)\n",
            "    stats['row_zero'] = (arr_np == 0).sum(axis=1).astype(np.float32)\n",
            "    stats['row_skew'] = skew(arr_np, axis=1).astype(np.float32)\n",
            "    stats['row_kurt'] = kurtosis(arr_np, axis=1).astype(np.float32)\n",
            "    return pd.DataFrame(stats)\n",
            "\n",
            "df_row_tr = compute_row_stats(X_num_tr.values.astype(np.float64))\n",
            "df_row_te = compute_row_stats(X_num_te.values.astype(np.float64))\n",
            "\n",
            "X_tr_all_numeric = pd.concat([X_num_tr.reset_index(drop=True), X_train_cat_encoded.reset_index(drop=True), df_row_tr.reset_index(drop=True)], axis=1)\n",
            "X_te_all_numeric = pd.concat([X_num_te.reset_index(drop=True), X_test_cat_encoded.reset_index(drop=True), df_row_te.reset_index(drop=True)], axis=1)\n",
            "\n",
            "cat_start_idx = len(keep_num)\n",
            "cat_indices = list(range(cat_start_idx, cat_start_idx + len(cat_cols)))\n",
            "print(f\"  Purified Numerical Features: {len(keep_num)} (Dropped {len(all_drop)})\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ===================================================================\n",
            "# CELL 5: QuantileTransformer Assembly\n",
            "# ===================================================================\n",
            "X_tr_all_numeric = X_tr_all_numeric.fillna(0).replace([np.inf, -np.inf], 0).astype(np.float32)\n",
            "X_te_all_numeric = X_te_all_numeric.fillna(0).replace([np.inf, -np.inf], 0).astype(np.float32)\n",
            "\n",
            "num_feature_indices = [i for i in range(X_tr_all_numeric.shape[1]) if i not in cat_indices]\n",
            "X_tr_num_part = X_tr_all_numeric.iloc[:, num_feature_indices].values\n",
            "X_te_num_part = X_te_all_numeric.iloc[:, num_feature_indices].values\n",
            "X_tr_cat_part = X_tr_all_numeric.iloc[:, cat_indices].values.astype(np.int32)\n",
            "X_te_cat_part = X_te_all_numeric.iloc[:, cat_indices].values.astype(np.int32)\n",
            "\n",
            "qt = QuantileTransformer(n_quantiles=min(2000, len(X_tr_num_part)), output_distribution='normal', random_state=CFG['seed'], subsample=200_000)\n",
            "X_tr_qt = qt.fit_transform(X_tr_num_part).astype(np.float32)\n",
            "X_te_qt = qt.transform(X_te_num_part).astype(np.float32)\n",
            "\n",
            "X_tr_final = np.hstack([X_tr_qt, X_tr_cat_part])\n",
            "X_te_final = np.hstack([X_te_qt, X_te_cat_part])\n",
            "cat_indices_final = list(range(X_tr_qt.shape[1], X_tr_qt.shape[1] + len(cat_cols)))\n",
            "print(f\"  Final Feature Matrix: Train {X_tr_final.shape} | Test {X_te_final.shape}\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ===================================================================\n",
            "# CELL 6: Synthetic Test-Distribution Generator\n",
            "# ===================================================================\n",
            "N_SYNTHETIC = int(round(len(X_test_raw) * CFG['synthetic_multiplier']))\n",
            "frac_int = X_num_te.apply(lambda s: np.isclose(s.dropna(), np.round(s.dropna())).mean() if s.notna().any() else 1.0)\n",
            "INT_LIKE_MASK = (frac_int >= CFG['integer_like_threshold']).values\n",
            "\n",
            "rng = np.random.default_rng(CFG['seed'])\n",
            "sample_idx = rng.integers(0, len(X_num_te), size=N_SYNTHETIC)\n",
            "synth_num_prejitter = X_num_te.iloc[sample_idx].reset_index(drop=True).fillna(0)\n",
            "synth_cat_df = X_test_raw[cat_cols].iloc[sample_idx].reset_index(drop=True)\n",
            "\n",
            "vals = synth_num_prejitter.values.copy()\n",
            "jitter_eligible = (vals != 0) & (~INT_LIKE_MASK)[np.newaxis, :]\n",
            "mult = np.ones(vals.shape)\n",
            "mult[jitter_eligible] = 1.0 + rng.normal(loc=0.0, scale=CFG['jitter_frac'], size=int(jitter_eligible.sum()))\n",
            "synth_num_raw = pd.DataFrame(vals * mult, columns=keep_num)\n",
            "\n",
            "df_row_sy = compute_row_stats(synth_num_prejitter.values.astype(np.float64))\n",
            "synth_cat_encoded = pd.DataFrame(index=range(N_SYNTHETIC))\n",
            "for col in cat_cols:\n",
            "    synth_cat_encoded[col] = cat_encoders[col].transform(synth_cat_df[col].astype(str)).astype(np.int32)\n",
            "\n",
            "synth_num_all = pd.concat([synth_num_raw.reset_index(drop=True), df_row_sy.reset_index(drop=True)], axis=1).fillna(0).replace([np.inf, -np.inf], 0).astype(np.float32)\n",
            "synth_num_qt = qt.transform(synth_num_all.values).astype(np.float32)\n",
            "X_synth_final = np.hstack([synth_num_qt, synth_cat_encoded.values.astype(np.int32)])\n",
            "\n",
            "def make_cb_df(arr, cat_idx):\n",
            "    df = pd.DataFrame(arr)\n",
            "    for ci in cat_idx:\n",
            "        df.iloc[:, ci] = df.iloc[:, ci].round().astype(int).astype(str)\n",
            "    return df\n",
            "\n",
            "X_te_cb_df = make_cb_df(X_te_final, cat_indices_final)\n",
            "X_sy_cb_df = make_cb_df(X_synth_final, cat_indices_final)\n",
            "print(f\"  Synthetic Test Matrix Generated: {X_synth_final.shape}\")\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ===================================================================\n",
            "# CELL 7: 10-Seed 5-Fold Training & Pseudo-Labeling\n",
            "# ===================================================================\n",
            "ENSEMBLE_SEEDS = CFG['ensemble_seeds']\n",
            "N_FOLDS = CFG['n_folds']\n",
            "n_base = len(y)\n",
            "n_test = len(X_te_final)\n",
            "\n",
            "oof_cb = np.zeros((n_base, len(ENSEMBLE_SEEDS)), dtype=np.float32)\n",
            "test_cb = np.zeros((n_test, len(ENSEMBLE_SEEDS)), dtype=np.float32)\n",
            "synth_cb = np.zeros((N_SYNTHETIC, len(ENSEMBLE_SEEDS)), dtype=np.float32)\n",
            "STAGE1_FOLDS = {}\n",
            "\n",
            "for seed_idx, seed in enumerate(ENSEMBLE_SEEDS):\n",
            "    skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=seed)\n",
            "    STAGE1_FOLDS[seed] = list(skf.split(X_tr_final, y))\n",
            "    oof_seed = np.zeros(n_base, dtype=np.float32)\n",
            "    for fold, (tr_idx, va_idx) in enumerate(STAGE1_FOLDS[seed]):\n",
            "        X_tr_fold, y_tr_fold = X_tr_final[tr_idx], y.iloc[tr_idx].values\n",
            "        X_va_fold, y_va_fold = X_tr_final[va_idx], y.iloc[va_idx].values\n",
            "        sm = SMOTE(sampling_strategy=CFG['smote_strategy'], random_state=seed + fold)\n",
            "        X_tr_sm, y_tr_sm = sm.fit_resample(X_tr_fold, y_tr_fold)\n",
            "        X_tr_sm_cb = make_cb_df(X_tr_sm, cat_indices_final)\n",
            "        X_va_cb    = make_cb_df(X_va_fold, cat_indices_final)\n",
            "        cb_params = CFG['cb_params'].copy()\n",
            "        cb_params['random_seed'] = seed\n",
            "        cb = CatBoostClassifier(**cb_params)\n",
            "        cb.fit(X_tr_sm_cb, y_tr_sm, cat_features=cat_indices_final, eval_set=[(X_va_cb, y_va_fold)], early_stopping_rounds=150, verbose=0)\n",
            "        oof_seed[va_idx] = cb.predict_proba(X_va_cb)[:, 1].astype(np.float32)\n",
            "        test_cb[:, seed_idx] += cb.predict_proba(X_te_cb_df)[:, 1].astype(np.float32) / N_FOLDS\n",
            "        synth_cb[:, seed_idx] += cb.predict_proba(X_sy_cb_df)[:, 1].astype(np.float32) / N_FOLDS\n",
            "        del X_tr_fold, X_va_fold, X_tr_sm, X_tr_sm_cb, X_va_cb, cb; gc.collect()\n",
            "    oof_cb[:, seed_idx] = oof_seed\n",
            "    print(f\"  Seed {seed} Stage 1 OOF F1@0.5: {f1_score(y, (oof_seed >= 0.5).astype(int)):.5f}\")\n",
            "\n",
            "oof_stage1 = np.mean(oof_cb, axis=1)\n",
            "test_stage1 = np.mean(test_cb, axis=1)\n",
            "synth_stage1 = np.mean(synth_cb, axis=1)\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ===================================================================\n",
            "# CELL 8: Stage 2 Fold-Safe Pseudo-Label Retraining\n",
            "# ===================================================================\n",
            "pos_thresh_cur = CFG['pseudo_pos_thresh']\n",
            "while ((synth_stage1 > pos_thresh_cur).sum() < CFG['pseudo_min_accept'] and pos_thresh_cur - CFG['pseudo_relax_step'] >= 0.5 + CFG['pseudo_relax_floor_margin']):\n",
            "    pos_thresh_cur = round(pos_thresh_cur - CFG['pseudo_relax_step'], 4)\n",
            "neg_thresh_cur = CFG['pseudo_neg_thresh']\n",
            "while ((synth_stage1 < neg_thresh_cur).sum() < CFG['pseudo_min_accept'] and neg_thresh_cur + CFG['pseudo_relax_step'] <= 0.5 - CFG['pseudo_relax_floor_margin']):\n",
            "    neg_thresh_cur = round(neg_thresh_cur + CFG['pseudo_relax_step'], 4)\n",
            "\n",
            "pos_idx = np.where(synth_stage1 > pos_thresh_cur)[0]\n",
            "neg_idx = np.where(synth_stage1 < neg_thresh_cur)[0]\n",
            "if len(neg_idx) > CFG['pseudo_max_neg_pos_ratio'] * max(len(pos_idx), 1):\n",
            "    neg_idx = rng.choice(neg_idx, size=int(CFG['pseudo_max_neg_pos_ratio'] * max(len(pos_idx), 1)), replace=False)\n",
            "\n",
            "SYNTH_SKIPPED = (len(pos_idx) == 0) or (not CFG['enable_stage2'])\n",
            "if not SYNTH_SKIPPED:\n",
            "    pseudo_labels = np.full(N_SYNTHETIC, -1, dtype=int)\n",
            "    pseudo_labels[pos_idx] = 1\n",
            "    pseudo_labels[neg_idx] = 0\n",
            "    acc_idx = np.concatenate([pos_idx, neg_idx])\n",
            "    acc_X, acc_y = X_synth_final[acc_idx], pseudo_labels[acc_idx]\n",
            "    \n",
            "    oof_cb2 = np.zeros((n_base, len(ENSEMBLE_SEEDS)), dtype=np.float32)\n",
            "    test_cb2 = np.zeros((n_test, len(ENSEMBLE_SEEDS)), dtype=np.float32)\n",
            "    for seed_idx, seed in enumerate(ENSEMBLE_SEEDS):\n",
            "        oof_seed = np.zeros(n_base, dtype=np.float32)\n",
            "        for fold, (tr_idx, va_idx) in enumerate(STAGE1_FOLDS[seed]):\n",
            "            X_tr_fold = np.vstack([X_tr_final[tr_idx], acc_X])\n",
            "            y_tr_fold = np.concatenate([y.iloc[tr_idx].values, acc_y])\n",
            "            X_va_fold, y_va_fold = X_tr_final[va_idx], y.iloc[va_idx].values\n",
            "            sm = SMOTE(sampling_strategy=CFG['smote_strategy'], random_state=seed + fold)\n",
            "            X_tr_sm, y_tr_sm = sm.fit_resample(X_tr_fold, y_tr_fold)\n",
            "            X_tr_sm_cb = make_cb_df(X_tr_sm, cat_indices_final)\n",
            "            X_va_cb    = make_cb_df(X_va_fold, cat_indices_final)\n",
            "            cb_params = CFG['cb_params'].copy()\n",
            "            cb_params['random_seed'] = seed\n",
            "            cb = CatBoostClassifier(**cb_params)\n",
            "            cb.fit(X_tr_sm_cb, y_tr_sm, cat_features=cat_indices_final, eval_set=[(X_va_cb, y_va_fold)], early_stopping_rounds=150, verbose=0)\n",
            "            oof_seed[va_idx] = cb.predict_proba(X_va_cb)[:, 1].astype(np.float32)\n",
            "            test_cb2[:, seed_idx] += cb.predict_proba(X_te_cb_df)[:, 1].astype(np.float32) / N_FOLDS\n",
            "            del X_tr_fold, X_va_fold, X_tr_sm, X_tr_sm_cb, X_va_cb, cb; gc.collect()\n",
            "        oof_cb2[:, seed_idx] = oof_seed\n",
            "    final_test_preds = np.mean(test_cb2, axis=1)\n",
            "else:\n",
            "    final_test_preds = test_stage1\n"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ===================================================================\n",
            "# CELL 9: Final Deterministic Binary Submission @ t=0.375\n",
            "# ===================================================================\n",
            "winning_t = CFG['winning_threshold']  # 0.375\n",
            "binary_preds = (final_test_preds >= winning_t).astype(int)\n",
            "\n",
            "out_dir = Path('/kaggle/working') if os.path.isdir('/kaggle/working') else Path('.')\n",
            "out_dir.mkdir(exist_ok=True)\n",
            "sub_path = out_dir / 'submission.csv'\n",
            "\n",
            "sub = pd.DataFrame({\n",
            "    'id': test_ids,\n",
            "    'TARGET': binary_preds\n",
            "})\n",
            "sub.to_csv(sub_path, index=False)\n",
            "\n",
            "n_pos = int(binary_preds.sum())\n",
            "pos_pct = (n_pos / len(sub)) * 100\n",
            "print(\"=\" * 75)\n",
            "print(f\"  🏆 SUCCESS! Generated Official Submission: {sub_path}\")\n",
            "print(f\"  Total Rows: {len(sub):,} | Positives Predicted (@ t={winning_t:.3f}): {n_pos:,} ({pos_pct:.2f}%)\")\n",
            "print(f\"  Elapsed Time: {(time.time() - T_START)/60:.2f} minutes\")\n",
            "print(\"=\" * 75)\n"
        ]
    }
]

nb = {
    "cells": nb_cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11.0"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

dst = 'final-submission/INFERENCE_NOTEBOOK.ipynb'
with open(dst, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Created {dst} successfully with {len(nb_cells)} cells!")
